releasetools: do not remove dynamic partitions in system-only builds
releasetools: do not remove dynamic partitions in system-only builds

* Before this commit, the generated `dynamic_partitions_op_list` in
  FullOTA packages always tries to remove all partitions and recreate
  them upon flashing. This makes it impossible to have a system-only
  "FullOTA" because vendor partition(s) are always removed.

* This commit detects if a build is vendor-less and disables every
  dynamic partition operation except `resize`, in order to keep the
  original content around after the flash. The change should not affect
  non-dynamic-partition or builds with vendor image included.

Change-Id: I0cded7f3b2958f35103d73d19b7fb5f292f6c17f
Signed-off-by: Jesse Chan <jc@lineageos.org>
Signed-off-by: SagarMakhar <sagarmakhar@gmail.com>

releasetools: ota_from_target_files: fix build for A-Only dynamic devices not building vendor

The function `HasVendorParition()` was moved inside `HasTrebleEnabled()` in 9276cf0226d341927d0a7e682a8db677e25ae5dd
It also has a different implementation now

`HasPartition()` which was used by it earlier is still present, using the same implementation, so use that directly

Fixes the following error

Traceback (most recent call last):
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2300, in <module>
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2279, in main
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2019, in GenerateNonAbOtaPackage
  File "/home/akhil/eleven/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 855, in WriteFullOTAPackage
NameError: global name 'HasVendorPartition' is not defined

Change-Id: I9bd4ebc9d6b103cfd572bfd5eacd3f7a5b1a661c
Signed-off-by: Akhil Narang <me@akhilnarang.dev>

Signed-off-by: ShubhamB <shubhamprince111@gmail.com>
Signed-off-by: SagarMakhar <sagarmakhar@gmail.com>
Change-Id: If7addd67072905ab31b3d462e647e8fbd20902ea
Signed-off-by: spezi77 <spezi7713@gmx.net>