Revert "build: set custom fingerprint in ro.build.fingerprint too"
This reverts commit dd7d4bb5c6e6f829152d24c3988b5fc223d6bc88.

Reason: Caused a conflict when using static sysprops in device tree.

error: found duplicate sysprop assignments

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: Ie87f9751642d744e9c7944158e40a1eeef8dc32b